In [32]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [33]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [34]:
model=LinearRegression()
model.fit(df[['area']],df["price"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
model.predict([[5000]])

array([859554.79452055])

In [36]:
import pickle

In [37]:
# Save Model To a File Using Python Pickle
with open('pickle_model','wb') as file:
    pickle.dump(model,file)

In [38]:
# Load Saved Model
with open('pickle_model','rb') as file:
    my_pickle_model = pickle.load(file)

In [39]:
my_pickle_model.predict([[5000]])

array([859554.79452055])

In [40]:
from sklearn.externals import joblib

In [41]:
# Save Trained Model Using joblib

joblib.dump(model, 'joblib_model')

['joblib_model']

In [45]:
# Loading the Model
my_joblib_model = joblib.load('joblib_model')

In [46]:
# Using the Model
my_joblib_model.predict([[5000]])

array([859554.79452055])