In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
df["bedrooms"].fillna(df["bedrooms"].median(),inplace=True)

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
model=LinearRegression()
new_df=df.drop("price",axis=1)
model.fit(new_df,df["price"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old
model.predict([[3000, 3, 40]])

array([498408.25158031])

In [17]:
# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old
model.predict([[2500,3,4]])

array([558718.87532003])

In [18]:
# salary for 2 yr experience, 9 test score, 6 interview score
model.predict([[2,9,6]])

array([412656.73999894])

In [ ]:
# salary for 12 yr experience, 10 test score, 10 interview score